base_url = "https://salif.github.io/linkita"

default_language = "bg"
author = "your_username"
generate_feeds = true
minify_html = true

[languages]

[languages.bg]
title = "Линкита"
description = "Линкита е многоезична, SEO оптимизирана, изчистена и елегантна блог тема за Zola."
# generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
  { name = "tags", feed = true, paginate_by = 5 },
  { name = "authors", feed = true, paginate_by = 5 },
]

[languages.en]
title = "Linkita"
description = "A clean and elegant blog theme for Zola. Linkita is based on Kita and Hugo-Paper and is multilingual and SEO friendly."
build_search_index = true
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
  { name = "tags", feed = true, paginate_by = 5 },
  { name = "authors", feed = true, paginate_by = 5 },
]

[languages.eo]
title = "Linkita"
description = "Pura kaj eleganta bloga temo por Zola. Linkita baziĝas sur Kita kaj Hugo-Paper kaj estas plurlingva kaj SEO-amika."
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
  { name = "tags", feed = true, paginate_by = 5 },
  { name = "authors", feed = true, paginate_by = 5 },
]

[languages.glb]
title = "Linkita"
generate_feeds = false
taxonomies = [
  { name = "tags", feed = true, paginate_by = 5 },
  { name = "authors", feed = true, paginate_by = 5 },
]

[languages.uwu]
title = "Linkita"
generate_feeds = false
description = "a cwean and ewegant bwog theme fow Zowa. Winkita is based on Kita and Hugo-Papew and is muwtiwinguaw and SEO fwiendwy. *nuzzles*"
taxonomies = [
  { name = "tags", feed = true, paginate_by = 5 },
  { name = "authors", feed = true, paginate_by = 5 },
]

[markdown]
highlight_code = true
extra_syntaxes_and_themes = []
highlight_theme = "monokai"

[extra]
math = false
mermaid = false
comment = false
title_separator = " | "
header_menu_name = "main"

[extra.style]
# bg_color = ""
# bg_dark_color = ""
# header_blur = true
# header_color = ""
# header_dark_color = ""

[extra.menus]
main = [
  { url = "$BASE_URL/projects/", name = "Projects", names_i18n = "common_projects" },
  { url = "$BASE_URL/archive/", name = "Archive", names_i18n = "common_archive" },
  { url = "$BASE_URL/tags/", name = "Tags", names_i18n = "common_tags" },
  { url = "$BASE_URL/about/", name = "About", names_i18n = "common_about" },
]
main_glb = [
  { url = "$BASE_URL/projects/", name = "Projects", names_i18n = "common_projects" },
  { url = "$BASE_URL/archive/", name = "Archive", names_i18n = "common_archive" },
  { url = "$BASE_URL/about/", name = "About", names_i18n = "common_about" },
]

[extra.profiles]

# Your profile
[extra.profiles.your_username]
avatar_url = "icons/github.svg"
avatar_invert = true
# avatar_alt = "Default alt text"
# name = "Default name"
# bio = "Default bio"
social = [
  { name = "codeberg", url = "https://codeberg.org/salif/linkita" },
  { name = "github", url = "https://github.com/salif/linkita" },
  { name = "rss", url = "$BASE_URL/atom.xml" },
]
[extra.profiles.your_username.languages]
[extra.profiles.your_username.languages.en]
name = "Linkita - Zola Theme"
bio = "A clean and elegant blog theme for Zola. Linkita is based on Kita and Hugo-Paper and is multilingual and SEO friendly."
avatar_alt = "Demo profile avatar."
[extra.profiles.your_username.languages.bg]
name = "Линкита - Тема за Зола"
bio = "Линкита е многоезична, SEO оптимизирана, изчистена и елегантна блог тема за Zola."
avatar_alt = "Демонстративен аватар за профила."
[extra.profiles.your_username.languages.eo]
name = "Linkita - Temo por Zola"
bio = "Pura kaj eleganta bloga temo por Zola. Linkita baziĝas sur Kita kaj Hugo-Paper kaj estas plurlingva kaj SEO-amika."
avatar_alt = "Demoprofila avataro."
[extra.profiles.your_username.languages.uwu]
name = "Linkita"
bio = "a cwean and ewegant bwog theme fow Zowa. Winkita is based on Kita and Hugo-Papew and is muwtiwinguaw and SEO fwiendwy. *nuzzles*"
[extra.profiles.your_username.open_graph]
image = "images/screenshot.png"
image_alt = "A screenshot of this website."
# fb_app_id = ""
# fb_admins = ["USER_ID"]
[extra.profiles.your_username.open_graph.languages]
bg = { image_alt = "Екранна снимка на този сайт." }
eo = { image_alt = "Ekrankopio de ĉi tiu retejo." }

# My profile
[extra.profiles.salif]
name = "Salif"
bio = "Hi! I'm the author."
email = "mail@salif.eu"
url = "https://salif.eu"
social = [
  { name = "codeberg", url = "https://codeberg.org/salif" },
  { name = "github", url = "https://github.com/salif" },
  { name = "bluesky", url = "https://bsky.app/profile/bg.salif.eu" },
  { name = "rss", url = "$BASE_URL/authors/salif/atom.xml" },
]
[extra.profiles.salif.languages]
[extra.profiles.salif.languages.bg]
name = "Салиф"
bio = "Здравейте! Аз съм авторът тук"
url = "https://salif.eu/bg/"
[extra.profiles.salif.languages.eo]
name = "Salif"
bio = "Saluton! Mi estas la aŭtoro"
url = "https://salif.eu/eo/"
[extra.profiles.salif.open_graph]
first_name = "Salif"
last_name = "Mehmed"
username = "salif"
gender = "male"
[extra.profiles.salif.open_graph.fediverse_creator]
handle = "bg.salif.eu"
domain = "bsky.brid.gy"
url = "https://bsky.brid.gy/r/https://bsky.app/profile/bg.salif.eu"

# Kita Theme's profile
[extra.profiles.kita]
name = "Kita"
bio = "Kita - Zola Theme"
url = "https://st1020.github.io/kita/"
social = [
  { name = "github", url = "https://github.com/st1020/kita" }
]

[extra.footer]
author_name = "Linkita"
since = 2020
license_name = "CC BY-SA 4.0"
license_url = "https://creativecommons.org/licenses/by-sa/4.0/deed"

[extra.languages]

[extra.languages.en]
locale = "en_US"
date_format = "%F"
date_format_archive = "%m-%d"

[extra.languages.bg]
locale = "bg_BG"
date_format = "%d %b %Y"
date_format_archive = "%d %b"

[extra.languages.eo]
locale = "eo"
date_format = "%d %b %Y"
date_format_archive = "%d %b"

[extra.languages.glb]
art_x_lang = "art-x-globasa"
header_menu_name = "main_glb"

[extra.languages.uwu]
art_x_lang = "art-x-uwu"

[extra.goatcounter]
endpoint = "https://sgi.goatcounter.com/count"
src = "//gc.zgo.at/count.js"

[extra.giscus]
repo = ""
repo_id = ""
category = ""
category_id = ""
mapping = "pathname"
strict = 1
reactions_enabled = 0
emit_metadata = 0
input_position = "top"
theme = "light"
lang = "en"
loading = "lazy"
