# The base URL of the site
base_url = "https://salif.github.io/linkita"

default_language = "bg"
author = "your_username"
generate_feeds = true

# Configuration of the Markdown rendering
[markdown]
# When set to "true", all code blocks are highlighted.
highlight_code = true

# A list of directories used to search for additional `.sublime-syntax` and `.tmTheme` files.
extra_syntaxes_and_themes = []

# The theme to use for code highlighting.
# See below for list of allowed values.
highlight_theme = "monokai"

[languages.bg]
title = "Линкита"
description = "Линкита е многоезична, SEO оптимизирана, изчистена и елегантна блог тема за Zola."
# generate_feeds = true
feed_filenames = ["atom.xml"]
[[languages.bg.taxonomies]]
name = "tags"
feed = true
paginate_by = 5
[[languages.bg.taxonomies]]
name = "authors"
feed = true
paginate_by = 5

[languages.en]
title = "Linkita"
description = "A clean and elegant blog theme for Zola. Linkita is based on Kita and Hugo-Paper and is multilingual and SEO friendly."
generate_feeds = true
feed_filenames = ["atom.xml"]
[[languages.en.taxonomies]]
name = "tags"
feed = true
paginate_by = 5
[[languages.en.taxonomies]]
name = "authors"
feed = true
paginate_by = 5

[languages.eo]
title = "Linkita"
description = "Pura kaj eleganta bloga temo por Zola. Linkita baziĝas sur Kita kaj Hugo-Paper kaj estas plurlingva kaj SEO-amika."
generate_feeds = true
feed_filenames = ["atom.xml"]
[[languages.eo.taxonomies]]
name = "tags"
feed = true
paginate_by = 5
[[languages.eo.taxonomies]]
name = "authors"
feed = true
paginate_by = 5

# English translations
[languages.en.translations]
language_name_en = "English"
language_name_bg = "Bulgarian"
language_name_eo = "Esperanto"
taxonomy_tags = "tags"
taxonomy_categories = "categories"
taxonomy_authors = "authors"
footer_powered_by = "Powered by"
footer_and = "and"
footer_zola = "Zola"
footer_linkita = "Linkita"
word_prev_page = "← Prev Page"
word_next_page = "Next Page →"
word_toc = "Table of Contents"
word_minutes = "min"
word_words = "words"
word_more = "More >>"
error_404 = "404"

# Bulgarian translations
[languages.bg.translations]
language_name_en = "английски"
language_name_bg = "български"
language_name_eo = "есперанто"
taxonomy_tags = "етикети"
taxonomy_categories = "категории"
taxonomy_authors = "автори"
footer_powered_by = "Осъществено чрез"
footer_and = "и"
footer_zola = "Зола"
footer_linkita = "Линкита"
word_prev_page = "← Предишна страница"
word_next_page = "Следваща страница →"
word_toc = "Съдържание"
word_minutes = "мин"
word_words = "думи"
word_more = "Още >>"
error_404 = "Грешка 404: Страницата не е намерена!"

# Esperanto translations
[languages.eo.translations]
language_name_en = "Angla"
language_name_bg = "Bulgara"
language_name_eo = "Esperanto"
taxonomy_tags = "etikedoj"
taxonomy_categories = "kategorioj"
taxonomy_authors = "aŭtoroj"
footer_powered_by = "Funkciigita de"
footer_and = "kaj"
footer_zola = "Zola"
footer_linkita = "Linkita"
word_prev_page = "← Antaŭa Paĝo"
word_next_page = "Sekva Paĝo →"
word_toc = "Enhavtabelo"
word_minutes = "min"
word_words = "vortoj"
word_more = "Pli >>"
error_404 = "404"

[extra]
math = false
mermaid = false
comment = false
show_updated_date = true
title_separator = " | "

[extra.style]
# bg_color = ""
# bg_dark_color = ""
# header_blur = true
# header_color = ""
# header_dark_color = ""

[extra.profiles]

# Your profile
[extra.profiles.your_username]
avatar_url = "icons/github.svg"
# avatar_alt = ""
avatar_invert = true
# name = "Default Name"
# bio = "Default Bio"

[extra.profiles.your_username.translations]
[extra.profiles.your_username.translations.en]
name = "Linkita - Zola Theme"
bio = "A clean and elegant blog theme for Zola. Linkita is based on Kita and Hugo-Paper and is multilingual and SEO friendly."
[extra.profiles.your_username.translations.bg]
name = "Линкита - Тема за Зола"
bio = "Линкита е многоезична, SEO оптимизирана, изчистена и елегантна блог тема за Zola."
[extra.profiles.your_username.translations.eo]
name = "Linkita - Temo por Zola"
bio = "Pura kaj eleganta bloga temo por Zola. Linkita baziĝas sur Kita kaj Hugo-Paper kaj estas plurlingva kaj SEO-amika."

[[extra.profiles.your_username.social]]
name = "codeberg"
url = "https://codeberg.org/salif/linkita"

[[extra.profiles.your_username.social]]
name = "github"
url = "https://github.com/salif/linkita"

[[extra.profiles.your_username.social]]
name = "rss"
url = "$BASE_URL/atom.xml"

[extra.profiles.your_username.open_graph]
image = "images/screenshot.png"
image_alt = "A screenshot of this website"
# fb_app_id = ""
# fb_admins = ["USER_ID"]

# My profile
[extra.profiles.salif]
name = "Salif"
bio = "Hi, I'm Salif"
email = "mail@salif.eu"
url = "https://salif.eu"
[extra.profiles.salif.translations]
[extra.profiles.salif.translations.bg]
name = "Салиф"
url = "https://salif.eu/bg/"
[extra.profiles.salif.open_graph]
first_name = "Salif"
last_name = "Mehmed"
username = "salif"
gender = "male"
fediverse_username = "bg.salif.eu"
fediverse_server = "bsky.brid.gy"
fediverse_url = "https://bsky.brid.gy/r/https://bsky.app/profile/bg.salif.eu"
[[extra.profiles.salif.social]]
name = "codeberg"
url = "https://codeberg.org/salif"
[[extra.profiles.salif.social]]
name = "github"
url = "https://github.com/salif"
[[extra.profiles.salif.social]]
name = "bluesky"
url = "https://bsky.app/profile/bg.salif.eu"
[[extra.profiles.salif.social]]
name = "rss"
url = "$BASE_URL/authors/salif/atom.xml"

# Kita Theme's profile
[extra.profiles.kita]
name = "Kita"
bio = "Kita - Zola Theme"
url = "https://st1020.github.io/kita/"
[[extra.profiles.kita.social]]
name = "github"
url = "https://github.com/st1020/kita"

# Menu
[[extra.menu]]
url = "$BASE_URL/projects/"
[extra.menu.names]
en = "Projects"
bg = "Проекти"
eo = "Projektoj"

[[extra.menu]]
url = "$BASE_URL/archive/"
[extra.menu.names]
en = "Archive"
bg = "Архив"
eo = "Arkivo"

[[extra.menu]]
url = "$BASE_URL/tags/"
[extra.menu.names]
en = "Tags"
bg = "Етикети"
eo = "Etikedoj"

[[extra.menu]]
url = "$BASE_URL/about/"
[extra.menu.names]
en = "About"
bg = "Относно"
eo = "Pri"

[extra.footer]
author_name = "Linkita"
since = 2020
license_name = "CC BY-SA 4.0"
license_url = "https://creativecommons.org/licenses/by-sa/4.0/deed"

[extra.locales.en]
locale = "en_US"
date_format = "%F"
date_format_archive = "%m-%d"

[extra.locales.bg]
locale = "bg_BG"
date_format = "%d %b %Y"
date_format_archive = "%d %b"

[extra.locales.eo]
locale = "eo"
date_format = "%d %b %Y"
date_format_archive = "%d %b"

[extra.reading_time]
en = ["reading_time"]
bg = ["reading_time"]
eo = ["word_count"]

[extra.goatcounter]
endpoint = "https://sgi.goatcounter.com/count"
src = "//gc.zgo.at/count.js"

[extra.giscus]
repo = ""
repo_id = ""
category = ""
category_id = ""
mapping = "pathname"
strict = 1
reactions_enabled = 0
emit_metadata = 0
input_position = "top"
theme = "light"
lang = "en"
loading = "lazy"
