# The base URL of the site
base_url = "https://salif.github.io/linkita"

default_language = "bg"
author = "Авторът"
title = "Линкита"
description = "Линкита е чиста и елегантна блог тема за Зола."
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [{ name = "tags", feed = true, paginate_by = 5 }]

# Configuration of the Markdown rendering
[markdown]
# When set to "true", all code blocks are highlighted.
highlight_code = true

# A list of directories used to search for additional `.sublime-syntax` and `.tmTheme` files.
extra_syntaxes_and_themes = []

# The theme to use for code highlighting.
# See below for list of allowed values.
highlight_theme = "monokai"

[languages.en]
title = "Linkita"
description = "Linkita is a multilingual, clean and elegant blog theme for Zola."
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [{ name = "tags", feed = true, paginate_by = 5 }]

[languages.eo]
title = "Linkita"
description = "Linkita estas pura kaj eleganta bloga temo por Zola."
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [{ name = "tags", feed = true, paginate_by = 5 }]

# English translations
[languages.en.translations]
language_name_en = "English"
language_name_bg = "Bulgarian"
language_name_eo = "Esperanto"
footer_powered_by = "Powered by"
footer_and = "and"
footer_zola = "Zola"
footer_linkita = "Linkita"
word_prev_page = "← Prev Page"
word_next_page = "Next Page →"
word_tags = "tags"
word_categories = "categories"
word_toc = "Table of Contents"
word_minutes = "min"
word_words = "words"
word_more = "More >>"
error_404 = "404"

# Bulgarian translations
[languages.bg.translations]
language_name_en = "английски"
language_name_bg = "български"
language_name_eo = "есперанто"
footer_powered_by = "Осъществено чрез"
footer_and = "и"
footer_zola = "Зола"
footer_linkita = "Линкита"
word_prev_page = "← Предишна страница"
word_next_page = "Следваща страница →"
word_tags = "етикети"
word_categories = "категории"
word_toc = "Съдържание"
word_minutes = "мин"
word_words = "думи"
word_more = "Още >>"
error_404 = "Грешка 404: Страницата не е намерена!"

# Esperanto translations
[languages.eo.translations]
language_name_en = "Angla"
language_name_bg = "Bulgara"
language_name_eo = "Esperanto"
footer_powered_by = "Funkciigita de"
footer_and = "kaj"
footer_zola = "Zola"
footer_linkita = "Linkita"
word_prev_page = "← Antaŭa Paĝo"
word_next_page = "Sekva Paĝo →"
word_tags = "etikedoj"
word_categories = "kategorioj"
word_toc = "Enhavtabelo"
word_minutes = "min"
word_words = "vortoj"
word_more = "Pli >>"
error_404 = "404"

# The Linkita theme style config.
[extra]
# Enable KaTex math formula support globally.
math = false
# Enable mermaid support globally.
mermaid = false
# Enable comment support globally.
comment = false
# Enable web analytics
# goatcounter_endpoint = "https://MYCODE.goatcounter.com/count"

[extra.style]
# The custom background color.
# bg_color = ""

# The custom background color in dark mode.
# bg_dark_color = ""

# Enable header blur.
# header_blur = true

# The custom header color, only available when `header_blur` is false.
# header_color = ""

# The custom header color in dark mode, only available when `header_blur` is false.
# header_dark_color = ""

# The profile on home page.
[extra.profile]
# The URL of avatar.
avatar_url = "icons/github.svg"
# Invert color in dark mode.
avatar_invert = true

[extra.profile.name]
en = "Linkita - Zola Theme"
bg = "Линкита - Тема за Зола"
eo = "Linkita - Temo por Zola"

[extra.profile.bio]
en = "Linkita is a multilingual, clean, and elegant blog theme for Zola."
bg = "Линкита е чиста и елегантна блог тема за Зола."
eo = "Linkita estas pura kaj eleganta bloga temo por Zola."

# The social icons below the profile on the home page.
# The `name` should be the file name of static/icons/*.svg or the icon name of https://simpleicons.org/
[[extra.profile.social]]
name = "github"
url = "https://github.com/salif/linkita"

[[extra.profile.social]]
name = "bluesky"
url = "https://github.com/salif/linkita"

[[extra.profile.social]]
name = "rss"
url = "$BASE_URL/atom.xml"

[extra.profile.open_graph]
# The URL of social image.
# image = "icons/github.svg"

# A name normally given to an individual by a parent or self-chosen.
# first_name = ""

# A name inherited from a family or marriage and by which the individual is commonly known.
# last_name = ""

# A short unique string to identify them.
# username = ""

# Their gender. enum(male, female).
# gender = ""

# fb_app_id = ""

# fb_admins = ["USER_ID"]

# Example for "@user@mastodon.social"
# fediverse_username = "user"
# fediverse_server = "mastodon.social"

# The top menu.
[[extra.menu]]
url = "$BASE_URL/projects/"
[extra.menu.name]
en = "Projects"
bg = "Проекти"
eo = "Projektoj"

[[extra.menu]]
url = "$BASE_URL/archive/"
[extra.menu.name]
en = "Archive"
bg = "Архив"
eo = "Arkivo"

[[extra.menu]]
url = "$BASE_URL/tags/"
[extra.menu.name]
en = "Tags"
bg = "Етикети"
eo = "Etikedoj"

[[extra.menu]]
url = "$BASE_URL/about/"
[extra.menu.name]
en = "About"
bg = "Относно"
eo = "Pri"

# The page footer options.
[extra.footer]
since = 2020
license_name = "CC BY-SA 4.0"
license_url = "https://creativecommons.org/licenses/by-sa/4.0/deed"

[extra.locales.en]
locale = "en_US"
date_format = "%F"
date_format_archive = "%m-%d"

[extra.locales.bg]
locale = "bg_BG"
date_format = "%d %b %Y"
date_format_archive = "%d %b"

[extra.locales.eo]
locale = "eo"
date_format = "%d %b %Y"
date_format_archive = "%d %b"

[extra.reading_time]
en = ["reading_time"]
bg = ["reading_time"]
eo = ["word_count"]

# The giscus comment options, only available when comment is enabled.
[extra.giscus]
repo = ""
repo_id = ""
category = ""
category_id = ""
mapping = "pathname"
strict = 1
reactions_enabled = 0
emit_metadata = 0
input_position = "top"
theme = "light"
lang = "en"
loading = "lazy"
