name = "Linkita"
description = "Linkita is a clean and elegant blog theme for Zola."
license = "MIT"
homepage = "https://github.com/salif/linkita"
min_version = "0.17.0"
demo = "https://salif.github.io/linkita/en/"

[author]
name = "Salif Mehmed"
homepage = "https://salif.eu"

[original]
author = "st1020"
homepage = "https://st1020.com"
repo = "https://github.com/st1020/kita"
