base_url = "https://salif.github.io/linkita"
theme = "linkita"

default_language = "en"
author = "sample_username"
compile_sass = false
minify_html = false
skip_content_templating = ["update-2/*"]
exclude_paginated_pages_in_sitemap = "all"
hard_link_static = false
generate_sitemap = true
generate_robots_txt = true

#[languages.en]
title = "Linkita"
description = "A clean and elegant blog theme for Zola. Linkita is based on Kita and Hugo-Paper and is multilingual and SEO friendly."
build_search_index = true
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
  { name = "tags", feed = true, paginate_by = 4 },
  { name = "authors", feed = true, paginate_by = 4 },
]

[languages.ar]
title = "لينكيتا"
description = "لينكيتا هو قالب مدونة زولا."
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
  { name = "tags", feed = false, paginate_by = 4 },
  { name = "authors", feed = false, paginate_by = 4 },
]

[languages.bg]
title = "Линкита"
description = "Линкита е многоезична, оптимизирана за търсачки, изчистена и елегантна блог тема за Зола."
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
  { name = "tags", feed = true, paginate_by = 4 },
  { name = "authors", feed = true, paginate_by = 4 },
]

[languages.cs]
title = "Linkita"
description = "Čistá a elegantní šablona blogu pro Zolu. Linkita je založena na šablonách Kita a Hugo-Paper, je vícejazyčná a přizpůsobená pro SEO."
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
  { name = "tags", feed = false, paginate_by = 4 },
  { name = "authors", feed = false, paginate_by = 4 },
]

[languages.eo]
title = "Linkita"
description = "Pura kaj eleganta bloga temo por Zola. Linkita baziĝas sur Kita kaj Hugo-Paper kaj estas plurlingva kaj SEO-amika."
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
  { name = "tags", feed = true, paginate_by = 4 },
  { name = "authors", feed = true, paginate_by = 4 },
]

[languages.es]
title = "Linkita"
description = "Un tema de blog para Zola, limpio y elegante. Linkita está basado en Kita y Hugo-Paper, es multilingüe y amigable con el SEO."
build_search_index = true
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
  { name = "tags", feed = false, paginate_by = 4 },
  { name = "authors", feed = false, paginate_by = 4 },
]

[languages.fi]
title = "Linkita"
description = "Puhdas ja elegantti blogiteema Zolalle. Linkita perustuu Kitaan ja Hugo-Paperiin ja on monikielinen sekä SEO-ystävällinen."
build_search_index = true
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
  { name = "tags", feed = false, paginate_by = 4 },
  { name = "authors", feed = false, paginate_by = 4 },
]

[languages.fr]
title = "Linkita"
description = "Un thème de blog propre et élégant pour Zola. Linkita est basé sur Kita et Hugo-Paper, il est multilingue et optimisé pour le SEO."
build_search_index = true
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
  { name = "tags", feed = false, paginate_by = 4 },
  { name = "authors", feed = false, paginate_by = 4 },
]

[languages.gb]
title = "Linkita"
description = ""
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
  { name = "tags", feed = false, paginate_by = 1 },
  { name = "authors", feed = false, paginate_by = 1 },
]

[languages.ja]
title = "Linkita"
description = "Zola用のクリーンでエレガントなブログテーマ。LinkitaはKitaとHugo-Paperをベースにしており、多言語対応とSEOフレンドリーな設計が特徴です。"
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
  { name = "tags", feed = false, paginate_by = 4 },
  { name = "authors", feed = false, paginate_by = 4 },
]

[languages.ko]
title = "Linkita"
description = "Zola를 위한 깔끔하고 우아한 블로그 테마입니다. Linkita는 Kita와 Hugo-Paper를 기반으로 하며, 다국어 지원 및 SEO에 친화적입니다."
build_search_index = true
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
  { name = "tags", feed = false, paginate_by = 4 },
  { name = "authors", feed = false, paginate_by = 4 },
]

[languages.tr]
title = "Linkita"
description = "Zola için temiz ve şık bir blog teması. Linkita, Kita ve Hugo-Paper'ı temel alır ve çok dilli ve SEO uyumludur."
build_search_index = true
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
  { name = "tags", feed = true, paginate_by = 4 },
  { name = "authors", feed = true, paginate_by = 4 },
]

[languages.zh]
title = "林基塔"
description = "林基塔 是一款适用于 左拉 的多语言、搜索引擎优化、简洁优雅的博客主题。"
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
  { name = "tags", feed = true, paginate_by = 4 },
  { name = "authors", feed = true, paginate_by = 4 },
]

[markdown]
render_emoji = false
smart_punctuation = false
definition_list = true
bottom_footnotes = true
github_alerts = true

[markdown.highlighting]
error_on_missing_language = true
style = "inline"
light_theme = "light-plus"
dark_theme = "github-dark-default"

[extra]
math = false
mermaid = false
comment = false
title_separator = " | "
header_menu_name = "sample_header"
header_buttons = ["site_title", "theme_select", "search_button", "translations_select"]
menu_i18n = true
use_cdn = false
relative_urls = false
ugly_urls = false
disable_default_favicon = false
page_summary_on_paginator = false
invert_page_navigation = false

[extra.style]
# bg_color = ""
# bg_dark_color = ""
# header_blur = true
# header_color = ""
# header_dark_color = ""

[extra.menus]
sample_header = [
  { url = "@base/projects/", name = "Projects" },
  { url = "@base/archive/", name = "Archive" },
  { url = "@base/tags/", name = "Tags" },
  { url = "@base/about/", name = "About" },
]

[extra.profiles]

# Linkita's profile
[extra.profiles.sample_username]
avatar_url = "icons/github.svg"
avatar_invert = true
# avatar_alt = "Default alt text"
# name = "Default name"
# bio = "Default bio"
social = [
  { name = "github", url = "https://github.com/salif/linkita" },
  { name = "rss", url = "@base/atom.xml" },
]
og_image = "images/screenshot.png"

[extra.profiles.sample_username.languages]
[extra.profiles.sample_username.languages.en]
name = "Linkita - Zola Theme"
bio = "A clean, elegant, and multilingual blog theme for Zola."
avatar_alt = "Demo profile avatar."
og_image_alt = "A screenshot of this website."
[extra.profiles.sample_username.languages.ar]
name = "لينكيتا - قوالب مدونة زولا"
bio = "لينكيتا هو قالب مدونة زولا."
avatar_alt = "الصورة الرمزية للملف الشخصي التجريبي"
og_image_alt = "لقطة شاشة لهذا الموقع." 
[extra.profiles.sample_username.languages.bg]
name = "Линкита - Тема за Зола"
bio = "Линкита е многоезична, оптимизирана за търсачки, изчистена и елегантна блог тема за Зола."
avatar_alt = "Демонстративен аватар за профила."
og_image_alt = "Екранна снимка на този сайт." 
[extra.profiles.sample_username.languages.cs]
name = "Linkita - Šablona pro Zolu"
bio = "Čistá a elegantní šablona blogu pro Zolu. Linkita je založena na šablonách Kita a Hugo-Paper, je vícejazyčná a přizpůsobená pro SEO."
avatar_alt = "Ukázkový profilový avatar."
og_image_alt = "Snímek obrazovky této webové stránky."
[extra.profiles.sample_username.languages.eo]
name = "Linkita - Temo por Zola"
bio = "Pura kaj eleganta bloga temo por Zola. Linkita baziĝas sur Kita kaj Hugo-Paper kaj estas plurlingva kaj SEO-amika."
avatar_alt = "Demoprofila avataro."
og_image_alt = "Ekrankopio de ĉi tiu retejo."
[extra.profiles.sample_username.languages.es]
name = "Linkita - Tema para Zola"
bio = "Un tema de blog para Zola, limpio y elegante. Linkita está basado en Kita y Hugo-Paper, es multilingüe y amigable con el SEO."
avatar_alt = "Avatar de perfil de demostración."
og_image_alt = "Una captura de pantalla de este sitio web."
[extra.profiles.sample_username.languages.fi]
name = "Linkita - Zola-teema"
bio = "Puhdas ja elegantti blogiteema Zolalle. Linkita perustuu Kitaan ja Hugo-Paperiin ja on monikielinen sekä SEO-ystävällinen."
avatar_alt = "Demon profiiliavatari."
og_image_alt = "Kuvakaappaus tältä verkkosivustolta."
[extra.profiles.sample_username.languages.fr]
name = "Linkita - Thème Zola"
bio = "Un thème de blog propre et élégant pour Zola. Linkita est basé sur Kita et Hugo-Paper, il est multilingue et optimisé pour le SEO."
avatar_alt = "Avatar de profil de démo."
og_image_alt = "Une capture d'écran de ce site web."
[extra.profiles.sample_username.languages.ja]
name = "Linkita - Zolaテーマ"
bio = "Zola用のクリーンでエレガントなブログテーマ。LinkitaはKitaとHugo-Paperをベースにしており、多言語対応とSEOフレンドリーな設計が特徴です。"
avatar_alt = "デモ用プロフィールのアバター"
og_image_alt = "このウェブサイトのスクリーンショット"
[extra.profiles.sample_username.languages.gb]
[extra.profiles.sample_username.languages.ko]
name = "Linkita - Zola 테마"
bio = "Zola를 위한 깔끔하고 우아한 블로그 테마입니다. Linkita는 Kita와 Hugo-Paper를 기반으로 하며, 다국어 지원 및 SEO에 친화적입니다."
avatar_alt = "데모 프로필 아바타입니다."
og_image_alt = "이 웹사이트의 스크린샷입니다."
[extra.profiles.sample_username.languages.tr]
name = "Linkita - Zola için Tema"
bio = "Zola için temiz ve şık bir blog teması. Linkita, Kita ve Hugo-Paper'ı temel alır ve çok dilli ve SEO uyumludur."
avatar_alt = "Demo profil avatarı."
og_image_alt = "Bu web sitesinin ekran görüntüsü."
[extra.profiles.sample_username.languages.zh]
name = "林基塔 - 左拉的主题"
bio = "林基塔 是一款适用于 左拉 的多语言、搜索引擎优化、简洁优雅的博客主题。"
avatar_alt = "演示个人资料头像。"
og_image_alt = "该网站的截图。"

# Salif's profile
[extra.profiles.salif]
name = "Salif"
bio = "Hi! I'm the author."

[extra.profiles.salif.languages]
[extra.profiles.salif.languages.ar]
name = "ساليف"
bio = "مرحبًا! انا المؤلف."
[extra.profiles.salif.languages.bg]
name = "Салиф"
bio = "Здравейте! Аз съм авторът тук."
[extra.profiles.salif.languages.cs]
name = "Salif"
bio = "Ahoj! Jsem autor."
[extra.profiles.salif.languages.eo]
name = "Salif"
bio = "Saluton! Mi estas la aŭtoro."
[extra.profiles.salif.languages.es]
name = "Salif"
bio = "¡Hola! Soy el autor."
[extra.profiles.salif.languages.fi]
name = "Salif"
bio = "Hei! Olen tämän teeman tekijä."
[extra.profiles.salif.languages.fr]
name = "Salif"
bio = "Salut ! Je suis l'auteur."
[extra.profiles.salif.languages.gb]
name = "Salif"
bio = "Salom! Mi sen eskriyen."
[extra.profiles.salif.languages.ja]
name = "Salif"
bio = "こんにちは！ 私が作者です。"
[extra.profiles.salif.languages.ko]
name = "Salif"
bio = "안녕하세요! 저는 이 테마의 제작자입니다."
[extra.profiles.salif.languages.tr]
name = "Salif"
bio = "Merhaba! Ben yazarım."
[extra.profiles.salif.languages.zh]
name = "萨利夫"
bio = "您好！我是作者。"

[[extra.profiles.salif.social]]
name = "home"
url = "https://salif.eu/"
[extra.profiles.salif.social.urls]
bg = "https://salif.eu/bg/"
eo = "https://salif.eu/eo/"
tr = "https://salif.eu/tr/"
[[extra.profiles.salif.social]]
name = "bluesky"
url = "https://bsky.app/profile/did:plc:eirne2vlczwdejeegserrfyr"
[[extra.profiles.salif.social]]
name = "tangled"
url = "https://tangled.org/yen.salif.eu"
[[extra.profiles.salif.social]]
name = "github"
url = "https://github.com/salif"
[[extra.profiles.salif.social]]
name = "rss"
url = "@base/authors/salif/atom.xml"

# Kita's profile
[extra.profiles.kita]
name = "Kita"
bio = "Linkita is based on st1020's Kita theme."
social = [
  { name = "github", url = "https://github.com/st1020/kita" },
  { name = "home", url = "https://kita-zola.pages.dev/" },
  { name = "rss", url = "@base/authors/kita/atom.xml" },
]

[extra.footer]
since = 2020
license_url = "https://creativecommons.org/licenses/by-sa/4.0/"
copyright = "&copy; $YEAR Linkita &vert; [CC BY-SA 4.0]($LICENSE_URL)"

[extra.languages]

[extra.languages.en]
locale = "en_US"
date_format = "%Y %b %-d"
page_info = [
  { when="date" },
  { when="date_updated", prepend="Upd. " },
  { when="reading_time", prepend="Est. " }
]
page_info_on_paginator = [{ when="date" }, { when="reading_time" }]
[extra.languages.en.taxonomy_descriptions]
tags = "A map of all tags on this site. Start exploring!"
authors = "A map of all authors on this site. Start exploring!"
[extra.languages.en.term_descriptions]
tags = "Browse articles related to $NAME. Start exploring!"
authors = "Browse articles written by $NAME. Start exploring!"

[extra.languages.ar]
locale = "ar_EG"
date_format = "%F"
[extra.languages.ar.taxonomy_descriptions]
tags = "خريطة لجميع الوسوم في هذا الموقع. ابدأ الاستكشاف!"
authors = "خريطة لجميع المؤلفين في هذا الموقع. ابدأ الاستكشاف!"
[extra.languages.ar.term_descriptions]
tags = "تصفح المقالات المتعلقة بـ $NAME. ابدأ الاستكشاف!"
authors = "تصفح المقالات التي كتبها $NAME. ابدأ الاستكشاف!"

[extra.languages.bg]
locale = "bg_BG"
date_format = "%F"
[extra.languages.bg.taxonomy_descriptions]
tags = "Разгледайте всички етикети на този сайт!"
authors = "Разгледайте всички автори на този сайт!"
[extra.languages.bg.term_descriptions]
tags = "Списък на страниците отнасящи се до $NAME."
authors = "Списък на страниците написани от $NAME."

[extra.languages.cs]
locale = "cs_CZ"
date_format = "%F"
[extra.languages.cs.taxonomy_descriptions]
tags = "Přehled všech štítků na tomto webu. Začněte prozkoumávat!"
authors = "Přehled všech autorů na tomto webu. Začněte prozkoumávat!"
[extra.languages.cs.term_descriptions]
tags = "Procházejte články související s $NAME. Začněte prozkoumávat!"
authors = "Procházejte články napsané autorem $NAME. Začněte prozkoumávat!"

[extra.languages.eo]
locale = "eo"
date_format = "%F"
[extra.languages.eo.taxonomy_descriptions]
tags = "Mapo de ĉiuj etikedoj en ĉi tiu retejo. Komencu esplori!"
authors = "Mapo de ĉiuj aŭtoroj en ĉi tiu retejo. Komencu esplori!"
[extra.languages.eo.term_descriptions]
tags = "Foliumu artikolojn rilatajn al $NAME. Komencu esplori!"
authors = "Foliumu artikolojn verkitajn de $NAME. Komencu esplori!"

[extra.languages.es]
locale = "es_ES"
date_format = "%F"
[extra.languages.es.taxonomy_descriptions]
tags = "Un mapa de todas las etiquetas de este sitio. ¡Empieza a explorar!"
authors = "Un mapa de todos los autores de este sitio. ¡Empieza a explorar!"
[extra.languages.es.term_descriptions]
tags = "Navega por los artículos relacionados con $NAME. ¡Empieza a explorar!"
authors = "Navega por los artículos escritos por $NAME. ¡Empieza a explorar!"

[extra.languages.fi]
locale = "fi_FI"
date_format = "%F"
[extra.languages.fi.taxonomy_descriptions]
tags = "Kartta kaikista tämän sivuston avainsanoista. Aloita tutkiminen!"
authors = "Kartta kaikista tämän sivuston kirjoittajista. Aloita tutkiminen!"
[extra.languages.fi.term_descriptions]
tags = "Selaa artikkeleita, jotka liittyvät avainsanaan $NAME. Aloita tutkiminen!"
authors = "Selaa kirjoittajan $NAME kirjoittamia artikkeleita. Aloita tutkiminen!"

[extra.languages.fr]
locale = "fr_FR"
date_format = "%F"
[extra.languages.fr.taxonomy_descriptions]
tags = "Plan de tous les tags sur ce site. Commencez l'exploration !"
authors = "Plan de tous les auteurs sur ce site. Commencez l'exploration !"
[extra.languages.fr.term_descriptions]
tags = "Parcourez les articles liés à $NAME. Commencez l'exploration !"
authors = "Parcourez les articles écrits par $NAME. Commencez l'exploration !"

[extra.languages.gb]
date_format = "%F"
num_format = "eo"
hreflang = "art-x-globasa"

[extra.languages.ja]
locale = "ja_JP"
date_format = "%F"
[extra.languages.ja.taxonomy_descriptions]
tags = "このサイトのすべてのタグ一覧です。好きなタグから探索を始めましょう！"
authors = "このサイトのすべての著者一覧です。好きな著者から探索を始めましょう！"
[extra.languages.ja.term_descriptions]
tags = "$NAME に関連する記事を閲覧します。探索を始めましょう！"
authors = "$NAME によって書かれた記事を閲覧します。探索を始めましょう！"

[extra.languages.ko]
locale = "ko_KR"
date_format = "%F"
[extra.languages.ko.taxonomy_descriptions]
tags = "이 사이트의 모든 태그 지도입니다. 탐색을 시작해보세요!"
authors = "이 사이트의 모든 작성자 지도입니다. 탐색을 시작해보세요!"
[extra.languages.ko.term_descriptions]
tags = "$NAME 관련 글을 둘러보세요. 탐색을 시작해보세요!"
authors = "$NAME 님이 작성한 글을 둘러보세요. 탐색을 시작해보세요!"

[extra.languages.tr]
locale = "tr_TR"
date_format = "%F"
[extra.languages.tr.taxonomy_descriptions]
tags = "Bu sitedeki tüm etiketlerin bir haritası. Keşfetmeye başlayın!"
authors = "Bu sitedeki tüm yazarların bir haritası. Keşfetmeye başlayın!"
[extra.languages.tr.term_descriptions]
tags = "$NAME ile ilgili makalelere göz atın. Keşfetmeye başlayın!"
authors = "$NAME tarafından yazılan makalelere göz atın. Keşfetmeye başlayın!"

[extra.languages.zh]
locale = "zh_CN"
date_format = "%F"
[extra.languages.zh.taxonomy_descriptions]
tags = "本站所有标签的地图。开始探索吧！"
authors = "本站所有作者的地图。开始探索吧！"
[extra.languages.zh.term_descriptions]
tags = "浏览与 $NAME 相关的文章。开始探索吧！"
authors = "浏览由 $NAME 撰写的文章。开始探索吧！"

# If you copy this file to your site, remove this:
[extra.goatcounter]
endpoint = "https://sgi.goatcounter.com/count"

[extra.giscus]
repo = ""
repo_id = ""
category = ""
category_id = ""
mapping = "pathname"
strict = 1
reactions_enabled = 0
emit_metadata = 0
input_position = "top"
theme = "preferred_color_scheme"
lang = "en"
loading = "lazy"
